import type { Product, Category } from "@/types/product";

export const products: Product[] = [
  {
    id: "p1",
    slug: "ashley-off-white-handbag",
    name: "Ashley Off White Handbag",
    description:
      "A structured everyday tote in soft off-white vegan leather. Magnetic closure, dual handles, and a roomy interior with a zipped pocket.",
    price: 2999,
    compareAtPrice: 3999,
    image: "/extracted/img-060.jpg",
    gallery: [
      "/extracted/img-061.png",
      "/extracted/img-062.jpg",
      "/extracted/img-063.png",
      "/extracted/img-064.jpg",
      "/extracted/img-065.png",
      "/extracted/img-066.jpg",
    ],
    category: "handbag",
    gender: "women",
    isNew: true,
    isBestSeller: true,
    isTrending: true,
    colors: ["#F1ECE3", "#1A1A1A", "#B98E5A"],
    features: ["Structured vegan leather body", "Magnetic snap closure", "Dual top handles", "Interior zip pocket", "Detachable shoulder strap"],
    specs: { Dimensions: "10 x 7 inches (L x H)", "Handle Drop": "8 inches", Material: "Vegan Leather", Closure: "Magnetic Snap", Hardware: "Gold-Tone Accents" },
    rating: 4.6,
    reviewCount: 128,
  },
  {
    id: "p2",
    slug: "ashley-charcoal-handbag",
    name: "Ashley Charcoal Handbag",
    description: "The Ashley silhouette in graphite — pebbled finish, structured base.",
    price: 2999,
    compareAtPrice: 3999,
    image: "/extracted/img-070.jpg",
    gallery: [
      "/extracted/img-071.png",
      "/extracted/img-072.jpg",
      "/extracted/img-073.png",
      "/extracted/img-074.jpg",
      "/extracted/img-075.png",
    ],
    category: "handbag",
    gender: "women",
    isNew: true,
    colors: ["#2B2B2B"],
    features: ["Pebbled vegan leather finish", "Structured base", "Magnetic snap closure", "Dual top handles", "Interior slip pocket"],
    specs: { Dimensions: "10 x 7 inches (L x H)", "Handle Drop": "8 inches", Material: "Vegan Leather", Closure: "Magnetic Snap", Hardware: "Silver-Tone Accents" },
    rating: 4.5,
    reviewCount: 92,
  },
  {
    id: "p3",
    slug: "ashley-bone-tote",
    name: "Ashley Bone Tote",
    description: "Roomy tote in bone with tonal stitching.",
    price: 2999,
    compareAtPrice: 3999,
    image: "/extracted/img-080.jpg",
    gallery: [
      "/extracted/img-081.png",
      "/extracted/img-082.jpg",
      "/extracted/img-083.png",
      "/extracted/img-084.jpg",
      "/extracted/img-085.png",
    ],
    category: "tote-bag",
    gender: "women",
    isNew: true,
    colors: ["#E8E0D2"],
    features: ["Roomy open-top design", "Tonal stitching detail", "Dual shoulder handles", "Inner zip organizer pocket", "Reinforced base"],
    specs: { Dimensions: "14 x 12 inches (L x H)", "Handle Drop": "10 inches", Material: "Vegan Leather", Closure: "Open Top", Hardware: "Gold-Tone Accents" },
    rating: 4.4,
    reviewCount: 64,
  },
  {
    id: "p4",
    slug: "ashley-camel-flap",
    name: "Ashley Camel Flap",
    description: "Camel flap with magnetic closure and chain handle.",
    price: 2999,
    compareAtPrice: 3999,
    image: "/extracted/img-090.jpg",
    gallery: [
      "/extracted/img-091.png",
      "/extracted/img-092.jpg",
      "/extracted/img-093.png",
      "/extracted/img-094.jpg",
      "/extracted/img-095.png",
    ],
    category: "sling-bag",
    gender: "women",
    isNew: true,
    colors: ["#C9A77B"],
    features: ["Flap-over magnetic closure", "Gold-tone chain handle", "Adjustable crossbody strap", "Card slot interior", "Soft camel vegan leather"],
    specs: { Dimensions: "8.5 x 5 inches (L x H)", "Strap Drop": "22 inches", Material: "Vegan Leather", Closure: "Magnetic Flap", Hardware: "Gold-Tone Accents" },
    rating: 4.7,
    reviewCount: 81,
  },
  {
    id: "p5",
    slug: "valera-dome-bag",
    name: "Valera Dome Bag",
    description: "Dome silhouette in forest green vegan leather — top zip, detachable strap.",
    price: 2999,
    compareAtPrice: 3999,
    image: "/extracted/img-070.jpg",
    gallery: [
      "/extracted/img-076.jpg",
      "/extracted/img-077.png",
      "/extracted/img-078.jpg",
      "/extracted/img-079.png",
    ],
    category: "bucket-bag",
    gender: "women",
    isTrending: true,
    isBestSeller: true,
    colors: ["#3C4A2C"],
    features: ["Dome silhouette", "Top zip closure", "Detachable crossbody strap", "Interior slip pocket", "Forest green vegan leather"],
    specs: { Dimensions: "9 x 8 inches (L x H)", "Strap Drop": "24 inches", Material: "Vegan Leather", Closure: "Zip Around", Hardware: "Gold-Tone Accents" },
    rating: 4.8,
    reviewCount: 211,
  },
  {
    id: "p6",
    slug: "halo-mini-bag",
    name: "Halo Mini Bag",
    description: "Mini structured shoulder bag in deep ink. Sleek, light, every-occasion.",
    price: 2999,
    compareAtPrice: 3999,
    image: "/extracted/img-080.jpg",
    gallery: [
      "/extracted/img-086.jpg",
      "/extracted/img-087.png",
      "/extracted/img-088.jpg",
      "/extracted/img-089.png",
    ],
    category: "sling-bag",
    gender: "women",
    isTrending: true,
    colors: ["#1A1A1A"],
    features: ["Mini structured silhouette", "Top zip closure", "Adjustable shoulder strap", "Card & phone interior slots", "Lightweight everyday design"],
    specs: { Dimensions: "7 x 5 inches (L x H)", "Strap Drop": "20 inches", Material: "Vegan Leather", Closure: "Top Zipper", Hardware: "Silver-Tone Accents" },
    rating: 4.6,
    reviewCount: 143,
  },
  {
    id: "p7",
    slug: "cordia-bag",
    name: "Cordia Bag",
    description: "Lime-tone soft shoulder bag with chain handle. Statement piece.",
    price: 2999,
    compareAtPrice: 3999,
    image: "/extracted/img-090.jpg",
    gallery: [
      "/extracted/img-096.jpg",
      "/extracted/img-097.png",
      "/extracted/img-098.jpg",
      "/extracted/img-099.png",
    ],
    category: "sling-bag",
    gender: "women",
    isTrending: true,
    colors: ["#D9E76A"],
    features: ["Soft lime vegan leather", "Gold-tone chain handle", "Magnetic flap closure", "Statement color finish", "Lined interior with slip pocket"],
    specs: { Dimensions: "8 x 6 inches (L x H)", "Strap Drop": "21 inches", Material: "Vegan Leather", Closure: "Magnetic Flap", Hardware: "Gold-Tone Accents" },
    rating: 4.3,
    reviewCount: 57,
  },
  {
    id: "p8",
    slug: "siena-tote",
    name: "Siena Tote",
    description:
      "The hero. Hand-finished vegan leather, pure & minimal lines, hidden magnetic closure, lined interior with laptop sleeve.",
    price: 4499,
    compareAtPrice: 5999,
    image: "/extracted/img-010.jpg",
    gallery: [
      "/extracted/img-011.png",
      "/extracted/img-012.jpg",
      "/extracted/img-013.png",
      "/extracted/img-014.jpg",
      "/extracted/img-015.png",
      "/extracted/img-016.jpg",
    ],
    category: "tote-bag",
    gender: "women",
    isNew: true,
    isBestSeller: true,
    isTrending: true,
    colors: ["#C9A77B", "#1A1A1A"],
    features: ["Hand-finished vegan leather", "Hidden magnetic closure", "Dedicated laptop sleeve", "Fully lined interior", "Dual reinforced handles"],
    specs: { Dimensions: "15 x 13 inches (L x H)", "Handle Drop": "11 inches", Material: "Vegan Leather", Closure: "Magnetic Hidden", Hardware: "Gold-Tone Accents" },
    rating: 4.9,
    reviewCount: 322,
  },
  {
    id: "p9",
    slug: "atlas-laptop-bag",
    name: "Atlas Laptop Bag",
    description: "Padded laptop sleeve, structured silhouette, 15\" fit.",
    price: 3499,
    compareAtPrice: 4499,
    image: "/extracted/img-100.jpg",
    gallery: [
      "/extracted/img-101.png",
      "/extracted/img-102.jpg",
      "/extracted/img-103.png",
      "/extracted/img-104.jpg",
      "/extracted/img-105.png",
    ],
    category: "laptop-bag",
    gender: "unisex",
    isBestSeller: true,
    colors: ["#1A1A1A", "#B98E5A"],
    features: ["Fits 14\" Laptop", "Multiple Functional Pockets", "Secure Top Zipper Closure", "Adjustable & Detachable Sling", "Padded back panel"],
    specs: { Dimensions: "13 x 10 inches (L x H)", "Handle Drop": "10 inches", Material: "Vegan Leather", Closure: "Zip Around Closure", Hardware: "Gold-Tone Accents" },
    rating: 4.5,
    reviewCount: 88,
  },
  {
    id: "p10",
    slug: "north-backpack",
    name: "North Backpack",
    description: "Minimal everyday backpack with padded back panel and laptop sleeve.",
    price: 3299,
    compareAtPrice: 4299,
    image: "/extracted/img-090.jpg",
    gallery: [
      "/extracted/img-091.png",
      "/extracted/img-092.jpg",
      "/extracted/img-093.png",
    ],
    category: "backpack",
    gender: "unisex",
    isBestSeller: true,
    colors: ["#8C6A3E"],
    features: ["Padded back panel", "Dedicated laptop sleeve", "Front quick-access zip", "Adjustable padded straps", "Water-resistant lining"],
    specs: { Dimensions: "12 x 16 inches (L x H)", "Strap Drop": "Adjustable", Material: "Vegan Leather", Closure: "Top Zipper", Hardware: "Matte Black Accents" },
    rating: 4.6,
    reviewCount: 104,
  },
  {
    id: "p11",
    slug: "lyric-bucket-bag",
    name: "Lyric Bucket Bag",
    description: "Drawstring bucket bag in soft caramel.",
    price: 2799,
    compareAtPrice: 3799,
    image: "/extracted/img-070.jpg",
    gallery: [
      "/extracted/img-072.jpg",
      "/extracted/img-073.png",
      "/extracted/img-074.jpg",
    ],
    category: "bucket-bag",
    gender: "women",
    colors: ["#B98E5A"],
    features: ["Drawstring top closure", "Soft caramel vegan leather", "Detachable crossbody strap", "Inner slip pocket", "Lightweight silhouette"],
    specs: { Dimensions: "9 x 10 inches (L x H)", "Strap Drop": "23 inches", Material: "Vegan Leather", Closure: "Drawstring", Hardware: "Gold-Tone Accents" },
    rating: 4.4,
    reviewCount: 41,
  },
  {
    id: "p12",
    slug: "nova-wallet",
    name: "Nova Wallet",
    description: "Slim bifold wallet in vegan leather with card slots and a coin pouch.",
    price: 1299,
    compareAtPrice: 1799,
    image: "/extracted/img-060.jpg",
    gallery: [
      "/extracted/img-061.png",
      "/extracted/img-062.jpg",
      "/extracted/img-063.png",
      "/extracted/img-064.jpg",
    ],
    category: "wallet",
    gender: "unisex",
    colors: ["#1A1A1A"],
    features: ["Slim bifold design", "8 card slots", "Zip coin pouch", "Vegan leather exterior", "RFID-safe lining"],
    specs: { Dimensions: "4.5 x 3.5 inches (L x H)", "Card Slots": "8 slots", Material: "Vegan Leather", Closure: "Bifold", Hardware: "N/A" },
    rating: 4.5,
    reviewCount: 73,
  },
];

export const categories: Category[] = [
  { slug: "tote-bag", name: "Tote Bag", image: "/extracted/img-100.jpg" },
  { slug: "handbag", name: "Handbag", image: "/extracted/img-060.jpg" },
  { slug: "laptop-bag", name: "Laptop Bag", image: "/extracted/img-100.jpg" },
  { slug: "sling-bag", name: "Sling Bag", image: "/extracted/img-080.jpg" },
  { slug: "bucket-bag", name: "Bucket Bag", image: "/extracted/img-070.jpg" },
  { slug: "backpack", name: "Backpack", image: "/extracted/img-090.jpg" },
  { slug: "wallet", name: "Wallet", image: "/extracted/img-060.jpg" },
];

export const genderShelves = [
  { slug: "men", name: "MEN", image: "/extracted/img-080.jpg" },
  { slug: "women", name: "WOMEN", image: "/extracted/img-070.jpg" },
  { slug: "unisex", name: "UNISEX", image: "/extracted/img-090.jpg" },
] as const;

export const trustBadges = [
  { icon: "leaf", label: "Eco-Friendly" },
  { icon: "shield", label: "Vegan Leather" },
  { icon: "refresh", label: "Easy Returns" },
] as const;

export const customerReviews = [
  {
    id: "r1",
    name: "Anaya M.",
    avatar: "/extracted/img-100.jpg",
    rating: 4.5,
    text: "The stitching and finishing feel premium. Totally worth the price.",
  },
  {
    id: "r2",
    name: "Priya S.",
    avatar: "/extracted/img-013.png",
    rating: 5,
    text: "My third Kibana bag and the quality keeps improving. Obsessed.",
  },
  {
    id: "r3",
    name: "Sofia R.",
    avatar: "/extracted/img-015.jpg",
    rating: 5,
    text: "Perfect for everyday use. The design is minimalist yet elegant.",
  },
  {
    id: "r4",
    name: "Emma K.",
    avatar: "/extracted/img-017.jpg",
    rating: 4,
    text: "Love the craftsmanship. Highly recommended for anyone looking for quality.",
  },
];

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(slug: string) {
  return products.filter((p) => p.category === slug);
}
